/**
 * File: constants.js
 * Purpose: Application constants
 * Layer: Constants
 */

const USER_ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  SALES_ASSOCIATE: 'sales_associate',      // ✅ With underscore
  INVENTORY_CLERK: 'inventory_clerk'        // ✅ With underscore
};

const USER_STATUS = {
  ACTIVE: 'active',
  ON_LEAVE: 'on_leave',                     // ✅ With underscore
  INACTIVE: 'inactive'
};

const ERROR_CODES = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  
  // Authentication
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  
  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  
  // Resources
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  
  // Conflicts
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_LIMIT_REACHED',
  
  // Rate limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

const SUBSCRIPTION_LIMITS = {
  free: {
    MAX_EMPLOYEES: 5,
    MAX_PRODUCTS: 100,
    MAX_WAREHOUSES: 1
  },
  basic: {
    MAX_EMPLOYEES: 20,
    MAX_PRODUCTS: 1000,
    MAX_WAREHOUSES: 3
  },
  premium: {
    MAX_EMPLOYEES: -1, // unlimited
    MAX_PRODUCTS: -1,
    MAX_WAREHOUSES: -1
  }
};

const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  EMPLOYEE_REGISTERED: 'EMPLOYEE_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  SALE_CREATED: 'SALE_CREATED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED'
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  ERROR_CODES,
  SUBSCRIPTION_LIMITS,
  AUDIT_ACTIONS
};
